### ISSUE TITLE
How to use for pages with pagination?

### ISSUE THREAD

**Issue by tiwka19** [jlarmstrongiv/astro-i18n-aut#16]
I have a blog page. I want to make pagination there, so the name of my file is [...page].astro. However, I get an error when I want to declare locale inside a function 

`Cannot read properties of undefined (reading 'pathname')`

here's the full code for my page

```
---
import MainLayout from '../../layouts/Layout.astro';
import { getLocale, getLocaleUrlPrefix } from 'astro-i18n-aut';
import { getCollection, CollectionEntry } from 'astro:content';

export async function getStaticPaths({ paginate }) {
  const locale = getLocale(Astro.url) ?? 'en';
  const localeUrlPrefix = getLocaleUrlPrefix(Astro.url);
  const posts = (await getCollection('blog', (entry) => entry.slug.startsWith(`${locale}/`))).map<
    CollectionEntry<'blog'> & { href: string }
  >((post) => {
    return paginate(posts, {
      href: localeUrlPrefix + '/blog' + post.slug.replace(locale, '') + '/',
      ...post,
    });
  });
}
---
```

**Comment by jlarmstrongiv** [comment]
Hi @tiwka19 👋 

The key is splitting up the logic in `getStaticPaths` logic.  In `getStaticPaths`, the locale information will not exist yet, so you need to return the part of the paths after the locale, like `/post-1/` and `/post-2/`.

The astro head will be re-run with the correct locales, so the urls will be the `defaultLocale` (such as `/blog/post-1/`, `/blog/post-2/`) and your other locales (such as `/es/blog/post-1/` and `/es/blog/post-2/`)

Then, in the astro head, you can use the `getLocale` and `getEntry` to get the content that matches the correct url and locale.

Here’s an example:

```astro
---
import { CollectionEntry, getCollection, getEntry } from 'astro:content';
import BlogPost from '../../layouts/BlogPost.astro';
import { getLocale } from "astro-i18n-aut";
import { DEFAULT_LOCALE } from '../../consts';

export async function getStaticPaths() {
	const posts = await getCollection('blog', (entry) => entry.slug.startsWith(DEFAULT_LOCALE + "/"));
	return posts.map((post) => ({
		params: { slug: post.slug.replace(DEFAULT_LOCALE + "/", "") },
	}));
}

type Props = CollectionEntry<'blog'>;

const { slug } = Astro.params;
const locale = getLocale(Astro.url) ?? DEFAULT_LOCALE

const post = await getEntry({
  collection: "blog",
  slug: locale + '/' + slug,
});
if (!post) {
  return new Response(null, {
    status: 404,
    statusText: 'Not found',
  });
}
const { Content } = await post.render();
---

<BlogPost {...post.data}>
	<h1>{post.data.title}</h1>
	<Content />
</BlogPost>
```

Let me know if you have any questions!

**Comment by jlarmstrongiv** [comment]
@tiwka19 for pagination specifically, just combine the example above with the example from the astro docs https://docs.astro.build/en/core-concepts/routing/#pagination

```astro
---
export async function getStaticPaths({ paginate }) {
  const astronautPages = [{
    astronaut: 'Neil Armstrong',
  }, {
    astronaut: 'Buzz Aldrin',
  }, {
    astronaut: 'Sally Ride',
  }, {
    astronaut: 'John Glenn',
  }];
  // Generate pages from our array of astronauts, with 2 to a page
  return paginate(astronautPages, { pageSize: 2 });
}
// All paginated data is passed on the "page" prop
const { page } = Astro.props;
---

<!--Display the current page number. Astro.params.page can also be used!-->
<h1>Page {page.currentPage}</h1>
<ul>
  <!--List the array of astronaut info-->
  {page.data.map(({ astronaut }) => <li>{astronaut}</li>)}
</ul>
```

**Comment by tiwka19** [comment]
> @tiwka19 for pagination specifically, combine the example above with the example from the astro docs https://docs.astro.build/en/core-concepts/routing/#pagination
> 
> ```astro
> ---
> export async function getStaticPaths({ paginate }) {
>   const astronautPages = [{
>     astronaut: 'Neil Armstrong',
>   }, {
>     astronaut: 'Buzz Aldrin',
>   }, {
>     astronaut: 'Sally Ride',
>   }, {
>     astronaut: 'John Glenn',
>   }];
>   // Generate pages from our array of astronauts, with 2 to a page
>   return paginate(astronautPages, { pageSize: 2 });
> }
> // All paginated data is passed on the "page" prop
> const { page } = Astro.props;
> ---
> 
> 
> <h1>Page {page.currentPage}</h1>
> <ul>
>   
>   {page.data.map(({ astronaut }) => <li>{astronaut}</li>)}
> </ul>
> ```
> 
> > This generates the following pages, with 2 items to a page:
> > 
> > * `/astronauts/1` - Page 1: Displays “Neil Armstrong” and “Buzz Aldrin”
> > * `/astronauts/2` - Page 2: Displays “Sally Ride” and “John Glenn”

Hi. Thanks for the tip, but can you give me a hint on what to do if the blog is built from an API? How do I pass the current locale to graphql?

```
export async function getStaticPaths() {
  const directus = await getDirectusClient();
  const data = await directus.query(`
    query {
        use_cases {
            id
            slug
            translations(filter: { languages_code: { code: { _eq: "${locale}" } } }) {
              title
              description
              content
            }
        }
    }
`);
```

**Comment by jlarmstrongiv** [comment]
@tiwka19 

The general idea is that `astro-i18n-aut` creates and helps you detect locales for translations.  

While the pages are translated, the urls are only prefixed (not translated) for compatibility with the Astro sitemap integration:

- `/about`
- `/es/about`

The `getStaticPaths` function needs to return the params in the url path.  For example, `/blog/[slug].astro`.  It only needs the `my-first-blog-post`, since that same slug is used in every single language as:

- `/blog/my-first-blog-post`
- `/es/blog/my-first-blog-post`

Then, `astro-i18n-aut` will take that slug and generate pages for all of your locales.  

In the astro component head, you need to `getLocale(Astro.url)` and fetch (normally astro content collections, but in your cased a graphql api) the translated content for that specific slug `my-first-blog-post` and locale `es` or `en`.  In my example, it’s this code:

```ts
const post = await getEntry({
  collection: "blog",
  slug: locale + '/' + slug,
});
```

In your example, it’s passing the locale and slug to the graphql query.  GraphQL Queries usually have ways to pass in parameters, but that really depends on your framework and query fetcher.

**Comment by tiwka19** [comment]
> @tiwka19
> 
> Общая идея заключается в том, что он `astro-i18n-aut`создает и помогает вам определять локали для переводов.
> 
> Хотя страницы переведены, URL-адреса имеют только префиксы (не переводятся) для совместимости с интеграцией карты сайта Astro:
> 
> * `/about`
> * `/es/about`
> 
> Функция `getStaticPaths`должна вернуть параметры в URL-пути. Например, `/blog/[slug].astro`. Ему нужен только `my-first-blog-post`, поскольку один и тот же фрагмент используется в каждом языке как:
> 
> * `/blog/my-first-blog-post`
> * `/es/blog/my-first-blog-post`
> 
> Затем `astro-i18n-aut`возьмем этот фрагмент и создадим страницы для всех ваших локалей.
> 
> В заголовке astro-компонента вам необходимо `getLocale(Astro.url)`получить (обычно коллекции astro-контента, но в вашем случае — API-интерфейс Graphql) переведенный контент для этого конкретного фрагмента `my-first-blog-post`и локали `es`или `en`. В моем примере это такой код:
> 
> ```ts
> const post = await getEntry({
>   collection: "blog",
>   slug: locale + '/' + slug,
> });
> ```
> 
> В вашем примере он передает локаль и пул в запросgraphql. Запросы GraphQL обычно имеют способы передачи параметров, но это действительно зависит от вашей платформы и средства выборки запросов.
> 
> Добавление нумерации страниц аналогично, но теперь вы получаете несколько параметров/слагов/записей на одной странице, а не только одну.

@jlarmstrongiv If I declare a variable outside the getStaticPaths function, it doesn't work, I get the error `locale is not defined`

**Comment by tiwka19** [comment]
@jlarmstrongiv So I don't know how to pass the current locale to the graphlq query. I'm sorry, but I can't understand how your answer can help me

**Comment by tiwka19** [comment]
@jlarmstrongiv I attach the full code of the cases/[slug].astro page. I would be very grateful if you could show me where my error is

```js
---
import { getLocale } from "astro-i18n-aut";
import MainLayout from "@/layouts/Layout.astro";
import { getDirectusClient } from "@/utils/get-direcrtus-client";

const locale = getLocale(Astro.url) ?? "en";

export async function getStaticPaths() {
  const directus = await getDirectusClient();
  const data = await directus.query(`
    query {
        use_cases {
            id
            slug
            translations(filter: { languages_code: { code: { _eq: "en" } } }) {
              title
              description  
              content
            }
        }
    }
`);
  return data.use_cases.map((post: any) => {
    return {
      params: { slug: post.slug },
      props: { post },  
    };
  });
}

const { post } = Astro.props;
---

<MainLayout title="My Blog">
  <div class="container px-5 py-36 mx-auto" aria-label="New Blog Posts">
    <div class="grid grid-cols-3 gap-20">
      <div class="prose lg:col-span-2 prose-invert max-w-[780px] prose:lg">
        <Fragment set:html={post.translations[0].content} />
      </div>
    </div>
  </div>
</MainLayout>
```

**Comment by jlarmstrongiv** [comment]
@tiwka19 

For your first comment, are you on the latest version of `astro` and `astro-i18n-aut`?  On the previous major version of `astro-i18n-aut`, the `defaultLocale` was undefined by default, but that is no longer the case.

Also, please be aware that there is a bug in the latest v3 causing the `dev` server to respond with `404` errors when using `[slug].astro`.  The `build` and `preview` commands work fine.  See https://github.com/jlarmstrongiv/astro-i18n-aut/issues/19 for details

---

For your code snippet, you need to separate where you get your slug and where you get your data.  `getStaticPaths` only runs [once](https://github.com/jlarmstrongiv/astro-i18n-aut#usage), even though the url may be `/about` or `/ru/about`.  You should only fetch the `params[].slug` in the `getStaticPaths`.  Do not fetch anything else—no content, no title, no description, etc.  You can only fetch data that is the same in all locales.  `getLocale` will not work inside `getStaticPaths` since there is no url to parse.

After the `getStaticPaths` function in the astro component head, you can use the `getLocale` for the locale and `Astro.params` information to fetch the content for the current locale.  Outside the `getStaticPaths` function, you can send the `locale` and `slug` in a `directus.query` to fetch your title, description, content, etc.

**Comment by SerjSidelnikov** [comment]
> [@tiwka19](https://github.com/tiwka19) for pagination specifically, combine the example above with the example from the astro docs https://docs.astro.build/en/core-concepts/routing/#pagination
> 
> ---
> export async function getStaticPaths({ paginate }) {
>   const astronautPages = [{
>     astronaut: 'Neil Armstrong',
>   }, {
>     astronaut: 'Buzz Aldrin',
>   }, {
>     astronaut: 'Sally Ride',
>   }, {
>     astronaut: 'John Glenn',
>   }];
>   // Generate pages from our array of astronauts, with 2 to a page
>   return paginate(astronautPages, { pageSize: 2 });
> }
> // All paginated data is passed on the "page" prop
> const { page } = Astro.props;
> ---
> 
> 
> <h1>Page {page.currentPage}</h1>
> <ul>
>   
>   {page.data.map(({ astronaut }) => <li>{astronaut}</li>)}
> </ul>
> > This generates the following pages, with 2 items to a page:
> > 
> > * `/astronauts/1` - Page 1: Displays “Neil Armstrong” and “Buzz Aldrin”
> > * `/astronauts/2` - Page 2: Displays “Sally Ride” and “John Glenn”

Hi. Can you please provide an example of pagination? I'm not sure I understand it fully. Thank you.
