### ISSUE TITLE
EPERM: operation not permitted, rmdir

### ISSUE THREAD

**Issue by znrepo** [jlarmstrongiv/astro-i18n-aut#28]
Hi
I got a strange issue on my windows pc (yes, I know :P).
The building process seems okay, but at the end I got this:

![image](https://github.com/jlarmstrongiv/astro-i18n-aut/assets/79815897/855c7b1b-4d5f-44e8-84f9-7da1698dc862)

I run "pnpm run build" or "npm run build" directly from console, no IDE, nothing else.
I can delete these folders manually later without any issues.
"pnpm run dev" works fine, no issues.

What can it be?

**Comment by jlarmstrongiv** [comment]
`astro-i18n-aut` only generates the folders during build.  

As to why it can’t be removed on your windows machine, I’m not sure.  I’ve seen others build on windows successfully.  I don’t have windows and I can’t reproduce.

I use `fs.remove` from [`fs-extra`](https://www.npmjs.com/package/fs-extra), a popular library with utility methods for `fs`.

My only recommendation would be to google `EPERM: operation not permitted` and see if any of the stack overflow advice like `npm cache clean --force` or deleting and reinstalling your `node_modules` folder works.  It may be a permissions error on your machine.

If you find a solution, please post it here!  Unfortunately, I’ll have to close this issue since I can’t reproduce or investigate it.

**Comment by jlarmstrongiv** [comment]
P.S.
I recommend using WSL on Windows if you can

**Comment by znrepo** [comment]
Okay, I feel myself super-silly. For some reason, the "src" folder (or somewhat else) had incorrect attributes/permissions. I just reset them recursively and now everything works.

I apologize for the issue and thank you for the quick response, but I still don’t understand where read-only came from, but it’s definitely not related to your package.

btw, thanks a lot for this package! Works like a charm.

**Comment by jlarmstrongiv** [comment]
No worries 😄 glad you found it
