### ISSUE TITLE
i18nMiddleware TS error

### ISSUE THREAD

**Issue by MarvinXu** [jlarmstrongiv/astro-i18n-aut#34]
In new projects, `middleware.ts` shows an typescript error:
> Argument of type 'MiddlewareResponseHandler' is not assignable to parameter of type 'MiddlewareEndpointHandler'.

![image](https://github.com/jlarmstrongiv/astro-i18n-aut/assets/7382357/d3dc1466-2f51-4502-84ed-802bc3a293a3)

I think it's because Astro updated types in the new release of i18n feature. Speaking of that, what's your opinion on the new i18n feature?

**Comment by jlarmstrongiv** [comment]
Thanks @MarvinXu!  I’ve been planning to use the new integration middleware [feature](https://astro.build/blog/astro-350/#integration-hooks-to-add-middleware) so that you don’t have to configure the middleware at all—just haven’t gotten around to it quite yet.  I decided to try it first by making cors and helmet middleware for Astro, and bringing back what I’ve learned to [`astro-i18n-aut`](https://www.npmjs.com/package/astro-i18n-aut).  Certainly makes me miss express haha

As for the new i18n feature, I’m disappointed that it doesn’t support what this library can—rendering all locales, including an unprefixed default locale, using a single `page.astro` file.  I don’t want to generate or keep an Astro page file up to date for every locale I have.  I was actually hoping to retire this library, but it seems like I’ll need it for quite a while longer.

I’ll keep this issue open until I make a PR for the built-in [integration middleware](https://astro.build/blog/astro-350/#integration-hooks-to-add-middleware).

**Comment by MarvinXu** [comment]
>  I don’t want to generate or keep an Astro page file up to date for every locale I have.

ha, exactly the  reason I chose this integration :)

> I’ve been planning to use the new integration middleware [feature](https://astro.build/blog/astro-350/#integration-hooks-to-add-middleware) so that you don’t have to configure the middleware at all

This looks great! Looking forward to it~

**Comment by jlarmstrongiv** [comment]
Fixed in `0.5.0` 🎉 

Just remove the old [`astro-i18n-aut`](https://www.npmjs.com/package/astro-i18n-aut) middleware ([the](https://docs.astro.build/en/reference/integrations-reference/#addmiddleware-option) [integration](https://astro.build/blog/astro-350/#integration-hooks-to-add-middleware) handles it now)… 

…and everything will work the same!

**Comment by jlarmstrongiv** [comment]
> > I don’t want to generate or keep an Astro page file up to date for every locale I have.
>
> ha, exactly the reason I chose this integration :)

I encourage you to leave a comment and feedback in the [i18n routing RFC](https://github.com/withastro/roadmap/pull/734) 😄 I’d love to see Astro support it in core, or at least fix https://github.com/withastro/astro/issues/8241
