### ISSUE TITLE
Keeping a changelog

### ISSUE THREAD

**Issue by illright** [jlarmstrongiv/astro-i18n-aut#48]
Hey, thanks for the package, Astro's stock i18n options are really not cutting it yet. I started using this package with its v0.5.0, and the most recent version is v0.7.0. I wanted to upgrade, but found no changelog, so I had to go through commits to see what changed, and I'm not sure I got everything. Could you add a changelog please, and if you remember, make notes of what constituted the few past releases?

I suggest https://keepachangelog.com/en/1.1.0/, it's a great and readable format. I'm also willing to contribute a changelog, but I'm not sure I'm able to accurately follow the project's history

**Comment by jlarmstrongiv** [comment]
> Could you add a changelog please

I used to be very much into repository management, using things like [`changesets`](https://www.npmjs.com/package/@changesets/cli) and git hooks and other things.  As I’ve gone along, these tools eventually become outdated and hard to upgrade.  I just haven’t had the time to find one changelog manager I like, and I haven’t seen the absolute need for it either.  I probably won’t use [`keepachangelog`](https://www.npmjs.com/package/keep-a-changelog) in particular because of its low downloads / usage.  Somehow, I’ve managed to completely break [`changesets`](https://www.npmjs.com/package/@changesets/cli) on my machine, or I’d probably have used that by now.  I just haven’t gotten around to fixing it.

That said, I definitely see the importance and value of a changelog.  It’s very nice when it links with renovate / dependabot.  If you would like to make a manual `CHANGELOG.md` file, feel free to do that.  

> If you remember, make notes of what constituted the few past releases?… I'm also willing to contribute a changelog, but I'm not sure I'm able to accurately follow the project's history

Unfortunately, I would just do the same as you, look at the commit history.  The good news is that most changes now are bugfixes.  The main reason I use a minor version bump is just in case a change in historical behavior breaks someone’s site.  I see this repo as mostly feature complete, and the major changes going forward would be when Astro fixes core bugs.

I’ll close this issue for now.  If you would like to make a manual `CHANGELOG.md` file, I’ll look it over and merge it.  I’ll see if I can get [`changesets`](https://www.npmjs.com/package/@changesets/cli) working again on my machine, but no promises for now.
